export const projects = [
  {
    id: "projects",
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: "Projects",
    headline: "This Website",
    description:
      "This website was created as a showcase or portfolio using mainly React and Styled Components — and of course Javascript, HTML and CSS",
    buttonLabel: "Github",
    imgStart: false,
    img: require("../../images/undraw-hacker-mind-6-y85.svg").default,
    alt: "Ironhack logo",
    dark: false,
    primary: false,
    darkText: true,
  },
  {
    id: "projects",
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: "Projects",
    headline: "Card-Game challenge",
    description: `The react app fetches players data from a mockup backend and creates an overview of cards showing information of each player. If a card is selected, the card gets a red border and the info from the card is displayed in the details-box.
    \nFrom the control panel, it is possible to sort the cards (ascending and descending). Also is possible to submit the selected player and send its info-details to the mocked server.`,
    buttonLabel: "Github",
    imgStart: false,
    img: require("../../images/card-game.png"),
    alt: "Challenge to show react skills",
    dark: false,
    primary: false,
    darkText: true,
  },
  {
    id: "projects",
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: "Projects",
    headline: "React app for couples",
    description:
      "App created with React, Express, Node and MogoDB which tracks the state of relationships and provides insights to improve them",
    buttonLabel: "Github",
    imgStart: false,
    img: require("../../images/undraw_progressive_app_m-9-ms.svg").default,
    alt: "Ironhack logo",
    dark: false,
    primary: false,
    darkText: true,
  },
];

export const education = [
  {
    id: "education",
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: "Education",
    headline: "Web Development Bootcamp at Ironhack berlin",
    description:
      "Over 450 hours of intense training on MERN (MongoDB, Express, React and Node), Javascript, HTML and CSS, coding with pairs using tools as GIT",
    buttonLabel: "Learn more",
    imgStart: true,
    img: require("../../images/MrRoboto.png"),
    alt: "Coding projects",
    dark: true,
    primary: true,
    darkText: false,
  },
  {
    id: "education",
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: "Education",
    headline: "Complete React Native in 2022: Zero to Mastery (with Hooks)",
    description:
      "Over 450 hours of intense training on MERN (MongoDB, Express, React and Node), Javascript, HTML and CSS, coding with pairs using tools as GIT",
    buttonLabel: "Learn more",
    imgStart: true,
    img: require("../../images/MrRoboto.png"),
    alt: "Coding projects",
    dark: true,
    primary: true,
    darkText: false, 
  },
  {
    id: "education",
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: "Education",
    headline: "Understanding TypeScript - 2022 Edition",
    description: "Over 450 hours of intense training on MERN (MongoDB, Express, React and Node), Javascript, HTML and CSS, coding with pairs using tools as GIT",
    buttonLabel: "Learn more",
    imgStart: true,
    img: require("../../images/MrRoboto.png"),
    alt: "Coding projects",
    dark: true,
    primary: true,
    darkText: false, 
  },
  {
    id: "education",
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: "Education",
    headline: "Higher Education",
    description: "Bachelor in Philosophy (2018-currrently) and Bachelor in Education Science (2010-2014)",
    buttonLabel: "Learn more",
    imgStart: true,
    img: require("../../images/MrRoboto.png"),
    alt: "Coding projects",
    dark: true,
    primary: true,
    darkText: false, 
  },
];

export const homeObjOne = {
  id: "projects",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Projects",
  headline: "This Website",
  description:
    "This website was created as a showcase or portfolio using mainly React and Styled Components — and of course Javascript, HTML and CSS",
  buttonLabel: "Github",
  imgStart: false,
  img: require("../../images/undraw-hacker-mind-6-y85.svg").default,
  alt: "Ironhack logo",
  dark: false,
  primary: false,
  darkText: true,
};

export const homeObjTwo = {
  id: "projects",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Projects",
  headline: "Card-Game challenge",
  description: `The react app fetches players data from a mockup backend and creates an overview of cards showing information of each player. If a card is selected, the card gets a red border and the info from the card is displayed in the details-box. From the control panel, it is possible to sort the cards (ascending and descending). Also is possible to submit the selected player and send its info-details to the mocked server.`,
  buttonLabel: "Github",
  imgStart: false,
  img: require("../../images/card-game.png"),
  alt: "Challenge to show react skills",
  dark: false,
  primary: false,
  darkText: true,
};

export const homeObjThree = {
  id: "about",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Further Education",
  headline: "Web Development Bootcamp at Ironhack berlin",
  description:
    "Over 450 hours of intense training on MERN (MongoDB, Express, React and Node), Javascript, HTML and CSS, coding with pairs using tools as GIT",
  buttonLabel: "Github",
  imgStart: false,
  img: require("../../images/undraw_progressive_app_m-9-ms.svg").default,
  alt: "Ironhack logo",
  dark: false,
  primary: false,
  darkText: true,
};

export const homeObjFour = {
  id: "education",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Projects",
  headline: "Web Development Bootcamp at Ironhack berlin",
  description:
    "Over 450 hours of intense training on MERN (MongoDB, Express, React and Node), Javascript, HTML and CSS, coding with pairs using tools as GIT",
  buttonLabel: "Learn more",
  imgStart: true,
  img: require("../../images/MrRoboto.png"),
  alt: "Coding projects",
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObjFive = {
  id: "about",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Further Education",
  headline: "Web Development Bootcamp at Ironhack berlin",
  description:
    "Over 450 hours of intense training on MERN (MongoDB, Express, React and Node), Javascript, HTML and CSS, coding with pairs using tools as GIT",
  buttonLabel: "Start Now",
  imgStart: false,
  img: require("../../images/undraw_progressive_app_m-9-ms.svg").default,
  alt: "Ironhack logo",
  dark: false,
  primary: false,
  darkText: true,
};
