export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Tech Education',
    headline: 'Web Development Bootcamp at Ironhack berlin',
    description: 'Over 450 hours of intense training on MERN (MongoDB, Express, React and Node), Javascript, HTML and CSS, coding with pairs using tools as GIT',
    buttonLabel: 'Contact',
    imgStart: false,
    img: require('../../images/undraw-hacker-mind-6-y85.svg').default,
    alt: 'Ironhack logo',
    dark: true,
    primary: true,
    darkText: false,
}