export const homeObjOne = {
    id: 'about',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Tech Education',
    headline: 'Web Development Bootcamp at Ironhack berlin',
    description: 'Over 450 hours of intense training on MERN (MongoDB, Express, React and Node), Javascript, HTML and CSS, coding with pairs using tools as GIT',
    buttonLabel: 'Contact',
    imgStart: false,
    img: require('../../images/undraw-hacker-mind-6-y85.svg').default,
    alt: 'Ironhack logo',
    dark: false,
    primary: false,
    darkText: true,
}

export const homeObjTwo = {
    id: 'discover',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Projects',
    headline: 'Web Development Bootcamp at Ironhack berlin',
    description: 'Over 450 hours of intense training on MERN (MongoDB, Express, React and Node), Javascript, HTML and CSS, coding with pairs using tools as GIT',
    buttonLabel: 'Learn more',
    imgStart: true,
    img: require('../../images/MrRoboto.png'),
    alt: 'Coding projects',
    dark: true ,
    primary: true,
    darkText: false,
}

export const homeObjThree = {
    id: 'signup',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Further Education',
    headline: 'Web Development Bootcamp at Ironhack berlin',
    description: 'Over 450 hours of intense training on MERN (MongoDB, Express, React and Node), Javascript, HTML and CSS, coding with pairs using tools as GIT',
    buttonLabel: 'Start Now',
    imgStart: false,
    img: require('../../images/undraw_progressive_app_m-9-ms.svg').default,
    alt: 'Ironhack logo',
    dark: false,
    primary: false,
    darkText: true,
}